apiVersion: v1
kind: Namespace
metadata:
  name: talon-core

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: talon-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
        - name: core
          image: netapp.azurecr.io/taloncore 
          imagePullPolicy: IfNotPresent
          command: [ "entrypoint.bat"  ]
          ports:
            - containerPort: 6618
            - containerPort: 6619
            - containerPort: 6620
            - containerPort: 6621
            - containerPort: 6622
            - containerPort: 6623
            - containerPort: 6624
            - containerPort: 6625
            - containerPort: 6676
            - containerPort: 6678
            - containerPort: 5201
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 6678
#            initialDelaySeconds: 15
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 6678
#            initialDelaySeconds: 15
#            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: talon-core
  labels:
    name: core
spec:
  ports:
    - protocol: TCP
      name: http
      port: 6618
      targetPort: 6618
    - protocol: TCP
      name: http1
      port: 6619
      targetPort: 6619
    - protocol: TCP
      name: http2
      port: 6620
      targetPort: 6620
    - protocol: TCP
      name: http3
      port: 6621
      targetPort: 6621
    - protocol: TCP
      name: http4
      port: 6622
      targetPort: 6622
    - protocol: TCP
      name: http5
      port: 6623
      targetPort: 6623
    - protocol: TCP
      name: http6
      port: 6624
      targetPort: 6624
    - protocol: TCP
      name: http7
      port: 6625
      targetPort: 6625
    - protocol: TCP
      name: http8
      port: 6676
      targetPort: 6676
    - protocol: TCP
      name: http9
      port: 6678
      targetPort: 6678
    - protocol: TCP
      name: http10
      port: 5201
      targetPort: 5201
  selector:
    app: core
  type: LoadBalancer
